spring:
  mail:
    host: smtp.163.com
    username: 18897793826@163.com
    password: HCdTjWXQrsWWanPa
  rabbitmq:
    addresses: 111.228.53.34
    username: admin
    password: 123456Ok!
    virtual-host: /
  application:
    name: RayVue-backend
  security:
    jwt:
      key: liMingZhiYi
      expireTime: 7
    filter:
      order: -100
  data:
    redis:
      host: 111.228.53.34
      port: 6379
      password: 123456Ok!
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
